path:
  log_file: /home/user/example/log/file.txt
  strategy: /home/user/example/Trading_Bot/strategies/

address: 
  address_example
  50000

authkey:
  password_example

display:
  current_time: True

auto: True
