# Another example of a strategy configuration file
# 1 - Parameters for StrategyManager object
strat_manager_instance:
  id_strat: 1             # An number id for your strat (< 100).
  current_pos: -1.0       # Current position of the strategy {1, 0, -1}
  current_vol: 0.01176993 # Current volume set to the position
  frequency: 10           # Frequency in seconds e.g daily = 86400
  STOP: 50                # Optional number of iteration before stopping
  order: submit_and_leave # Kind of order object (see API documentation)

# 2 - Parameters for the strategy function
strategy_instance:
  args_params:          # Optional list of parameters to compute signal.
  - para1
  kwargs_params:        # Optional dict of parameters to compute signal
    target_vol: 0.2     # Correspond to 20% of yearly volatility
    leverage: 1.        # Correspond to the max leverage allowed
    half_life: 11       # Number of period to compute exponential vol
    period: 525600      # Number of trading period per year

# 3 - Parameters for DataRequest object
get_data_instance:
  source_data: exchange  # database or exchange available
  args:                  # Optional list of parameters
  - OHLC
  kwargs:                # Optional dict of parameters
    pair: XBTUSD
    interval: 60
  assets:                # List of assets to load from source_data
  - XXBTZUSD
  ohlcv: ohlcv           # {o: open, h: high, l: low, c: close, v: volume}
  frequency: 7200        # Number of second between two data
  n_min_obs: 50          # Minimal number of observation to compute signal
  path: https://api.kraken.com/0/public   # Path of the data source

# 4 - Parameters for set_order method, check API documentation
order_instance:
  pair: XXBTZUSD     # Symbol of underlying
  ordertype: market  # Order type e.g. limit or market
  leverage: 1        # Max leverage
  validate: true     # /!\ Doesn't push order if True /!\
  volume: 0.01176993 # Max volume to trade
