# Example of a strategy configuration file
# 1 - Parameters for StrategyManager object
strat_manager_instance:
  id_strat: 2        # An number id for your strat (< 100)
  current_pos: 0.0   # Current position of the strategy {1, 0, -1}
  current_vol: 0.0   # Current volume set to the position
  frequency: 30      # Frequency in seconds e.g. daily = 86400
  STOP: 30           # Optional number of iteration before stopping
  order: best_limit  # Kind of order object (see API documentation)
  reinvest: false    # Reinvest profit to trading volume

# 2 - Parameters for the strategy function
strategy_instance:
  args_params:      # Optional list of parameters to compute signal
  - 1
  - 0
  - -1
  kwargs_params:    # Optional dict of parameters to compute signal
    target_vol: 0.2 # Correspond to 20% of yearly volatility
    leverage: 1.    # Correspond to the max leverage allowed
    half_life: 11   # Number of period to compute exponential vol
    period: 525600  # Number of trading period per year

# 3 - Parameters for DataRequest object
get_data_instance:
  source_data: database  # database or exchange available
  args: []               # Optional list of parameters
  kwargs:                # Optional dict of parameters
    start: 1552089600
    last: 1552155180
  assets:                # List of assets to load from source_data
  - example
  - other_example
  ohlcv: v               # {o: open, h: high, l: low, c: close, v: volume}
  frequency: 60          # Number of second between two data
  n_min_obs: 5           # Minimal number of observation to compute signal
  path: ./data_base/     # Path of data source

# 4 - Parameters for set_order method, check API documentation
order_instance:
  pair: XETHZUSD    # Symbol of underlying
  ordertype: limit  # Order type e.g. limit or market
  leverage: 1       # Max leverage
  oflags: post      # comma delimited list of flags (optionaly)
  validate: true    # /!\ Doesn't push order if True /!\
  volume: 1.        # Max volume to trade without leverage
  order_params:     # Additional parameters

# 5 - Parameters to print some statistic of strategy
result_instance:
  # path: ./strategies/example/
  period: 364
  # init_vol: 100.
  # reinvest_profit: true
  metrics:
  - Return
  - Perf
  - Sharpe
  - Calmar
  - MaxDD
  periods:
  - Daily
  - Weekly
  - Monthly
  - Yearly
  - Total
